### PR TITLE
Make benchmark peer dependency

### PR DESCRIPTION
**Pull request by MichaReiser**
Make benchmark.js a peer dependency that a project might use a different version.
E.g. a version that points to a pull request.

### CODE REVIEW

**Comment by JamieMason** [comment]
First of all, thanks for contributing!

I've given this a try by changing the `karma-benchmark` entry in [examples/package.json](https://github.com/JamieMason/karma-benchmark/blob/82097ca6015ed8769fe0b97d349d560304fb4f74/examples/package.json#L6) to;

```
"karma-benchmark": "git+https://github.com/MichaReiser/karma-benchmark.git#ae5866dcaf28524f412c3105c6364e123dabf805",
```

When I run `npm test` I get the following error;

```
module.js:471
    throw err;
    ^

Error: Cannot find module './dist/karma-benchmark.js'
```

This is of course because of the change to a peer dependency and can be fixed by making sure that everyone who uses karma-benchmark knows to also manage its benchmark.js dependency themselves.

This would be a breaking change. Can you tell me more about it so I can better understand your motivations?

Thanks again for spending time on contributing to this project.

**Comment by MichaReiser** [comment]
The main reason for defining it as peer dependency is to be able to use a different version of benchmarkjs. 

In my case, I need the version that has support for async setup and teardown (not yet released).

**Comment by AleshaOleg** [comment]
Are there any updates? If I'll update this PR, will somebody merge this?

**Comment by JamieMason** [comment]
I'll pick it up, thanks

**Comment by AleshaOleg** [comment]
@JamieMason `npm run test` cause an error: `TypeError: Cannot set property 'start' of undefined`in `src/main.js:14:24`. Did tests work before? Because for me, after and before updating dependencies they not working.

**Comment by AleshaOleg** [comment]
Ok, I have a problem with `hoek` dependency in some of the packages and thought that a problem with `karma-benchmark`. That's why I wanted to help with package updating. I was wrong, problem in another package. Sorry.

@MichaReiser I think if you need t use `@next` version of `npm` package, you can install it manually in your package and use the latest features. And there is no need to ask somebody to install it as `peerDependencies`. Am I wrong?

**Comment by JamieMason** [comment]
> @JamieMason `npm run test` cause an error: `TypeError: Cannot set property 'start' of undefined`in `src/main.js:14:24`. Did tests work before? Because for me, after and before updating dependencies they not working.

Apologies, the tests are no good. There is one which I will remove for now. I'd love to pick this project back up and do a proper job of it but haven't had time yet.

**Comment by JamieMason** [comment]
Released as 1.0.0, please let me know if any changes are needed. Thanks so much for your help and sorry for the long wait.

**Pull request closed without merging**
